version: '3'
name: express-compose
services:
  api:
    container_name: express-compose-api
    image: node:latest
    volumes:
      - type: bind
        source: ./
        target: /code
    working_dir: /code
    ports: 
      - 3000:3000
    environment:
      - PORT=3000
    command: bash -c "npm install && npm run dev"
    
  